language: python

sudo: false

env:
    - TOX_ENV=py27-django1.6
    - TOX_ENV=py27-django1.7
    - TOX_ENV=py27-django1.8
    - TOX_ENV=py32-django1.6
    - TOX_ENV=py32-django1.7
    - TOX_ENV=py32-django1.8
    - TOX_ENV=py33-django1.6
    - TOX_ENV=py33-django1.7
    - TOX_ENV=py33-django1.8
    - TOX_ENV=py34-django1.6
    - TOX_ENV=py34-django1.7
    - TOX_ENV=py34-django1.8

matrix:
    fast_finish: true

before_install:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3 # give xvfb some time to start

install:
    - pip install tox

script:
    - tox -e $TOX_ENV